// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFvZRbZG0DwQo4gtxLSYbPGbIJroehz4U',
    appId: '1:645367763226:web:5223367a93d2702be09ca3',
    messagingSenderId: '645367763226',
    projectId: 'ftfl-dashboard',
    authDomain: 'ftfl-dashboard.firebaseapp.com',
    storageBucket: 'ftfl-dashboard.firebasestorage.app',
    measurementId: 'G-95YNYSMX7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7jn6z0-k2On5Ijzimb63iULsI7AHFo0',
    appId: '1:645367763226:android:d35536f3285ae454e09ca3',
    messagingSenderId: '645367763226',
    projectId: 'ftfl-dashboard',
    storageBucket: 'ftfl-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUP8CJGLWnJRnNrw_3dhbFLjUdyUAmEQ',
    appId: '1:645367763226:ios:1d6419ead22607c9e09ca3',
    messagingSenderId: '645367763226',
    projectId: 'ftfl-dashboard',
    storageBucket: 'ftfl-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.ftflDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUP8CJGLWnJRnNrw_3dhbFLjUdyUAmEQ',
    appId: '1:645367763226:ios:1d6419ead22607c9e09ca3',
    messagingSenderId: '645367763226',
    projectId: 'ftfl-dashboard',
    storageBucket: 'ftfl-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.ftflDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFvZRbZG0DwQo4gtxLSYbPGbIJroehz4U',
    appId: '1:645367763226:web:980343e96be762f6e09ca3',
    messagingSenderId: '645367763226',
    projectId: 'ftfl-dashboard',
    authDomain: 'ftfl-dashboard.firebaseapp.com',
    storageBucket: 'ftfl-dashboard.firebasestorage.app',
    measurementId: 'G-HGH4YXPTMQ',
  );
}
